### ISSUE TITLE
Replace Systemd as the init system in Nitrux

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-iso-tool#33]
Nitrux currently uses Systemd as the init system (that we inherited from Ubuntu, not as a choice by us). We prefer to follow the Unix way of doing things, "do one thing and do it well."

znx, for example, doesn't attempt to do more than what it was designed to do. Our focus on AppImages also indicates that we prefer to have to manage one file (the AppImage file) instead of a multitude of packages. Nitrux itself is deployed as one file by znx. The operating systems that VMetal runs are also contained as a single file.

Systemd is more than an init system that doesn't follow that way. See [Wikipedia:File:Systemd components.svg](http://en.wikipedia.org/wiki/File:Systemd_components.svg).

> systemd, **is a software suite**, full replacement for init in Linux that includes an init daemon[...]

With that said, we should considerate simplifying our distribution by using a more straightforward init system.

The following are the options:
- [s6-init](https://skarnet.org/software/s6-linux-init/), s6-Linux-init is a set of minimalistic tools used to create an s6-based init system, including a /sbin/init binary, on a Linux kernel.
- SysVinit, The traditional Linux SysV clone.
- runit, a full cross-platform replacement for init with parallel starting of services.
- OpenRC, a process spawner that utilizes system-provided init, while providing process isolation, parallelized startup, and service dependency.
- busybox-init, suited for embedded operating systems.

**Comment by UriHerrera** [comment]
I have managed to create a working image (no GUI) without SystemD. It's using SysVinit, but it's a start.

![VirtualBox_Nitrux_02_07_2019_09_14_17](https://user-images.githubusercontent.com/3053525/60520061-5a9b2080-9caa-11e9-9239-24116d42623f.png)

**Comment by UriHerrera** [comment]
I have modified a deployed development image. Once again, it's using SysV, but the news here is that there's a GUI and everything is precisely the same as the previous images, of course except for the init system.

![VirtualBox_Nitrux_24_09_2019_13_45_01](https://user-images.githubusercontent.com/3053525/65543020-e8fff680-ded5-11e9-8fd8-3a29b11e139f.png)

**Comment by anupam-git** [comment]
Finally after days of debugging loads of logs, you've succeded.. :100:

**Comment by UriHerrera** [comment]
### Using OpenRC
I have created another build based on the development branch; this build utilizes OpenRC. Unlike the previous build, there's no GUI, and there's no network.

Things that work:

- [x] Boots.

Things that don't work:

- [ ] SDDM.
- [ ] Desktop.
- [ ] Network.

### Screenshots

![VirtualBox_Nitrux_25_09_2019_23_49_09](https://user-images.githubusercontent.com/3053525/65658915-4045ba00-dfef-11e9-8811-bd7bff9aa06f.png)

### What's next
I'll try with other init system.

**Comment by alekstj** [comment]
- [ ] runit

**Comment by UriHerrera** [comment]
### Using runit as init and runit with SysV compatibility
I have created another build based on the development branch; this build utilizes runit. The system boots in both cases, using runit as /sbin/init and as an extension of SysV. The main problem is that it seems that not all services are started.

Things that work:

- [x] Boots (no Plymouth though; SDDM doesn't start automatically).
- [x] Persistence.

Things that don't work:

- [ ] Plymouth (doesn't work at all)
- [ ] X11 (SDDM starts but X11 freezes immediately).
- [ ] Network (?).

### Screenshots

No screenshots. It boots directly to the graphical session but X11 freezes and results in a black screen.

### What's next
Try to make one of these three init systems work.

**Comment by luis-lavaire** [comment]
How performant is `SysV`? As it's the one that works, perhaps we should focus on polishing that one. :slightly_smiling_face:

**Comment by UriHerrera** [comment]
> How performant is `SysV`? As it's the one that works, perhaps we should focus on polishing that one.

I measured the boot time from after selecting the deployed system on the znx boot menu and pressing enter until the welcome wizard shows up.

Current Development ISO with systemd: 00:46.67
Test build ISO with SysV: 00:48.56

**Comment by luis-lavaire** [comment]
The same boot time for both `SysV` and `systemd`? That is weird.

**Comment by anupam-git** [comment]
Which are the ones with huge bootup time as shown in `systemd-analyze blame` ?

**Comment by luis-lavaire** [comment]
`systemd` was supposed to reduce boot times. :man_shrugging:

**Comment by UriHerrera** [comment]
![VirtualBox_Nitrux_30_09_2019_02_00_20](https://user-images.githubusercontent.com/3053525/65856003-1c071780-e326-11e9-9437-6b9cb0ea38cd.png)

**Comment by UriHerrera** [comment]
As per my findings in #41, the boot time is now on the test build ISO without systemd and using SysV of boots in VirtualBox in 00:21:54 seconds vs. the 00:22:28 seconds. That is, the ISO booted directly, not after deploying the operating system.

**Comment by sshyran** [comment]
small, but mindblowing feature request: how about implementing "runit"... to supplement portability and crossplatformity in 30 sec. timeframe ?

**Comment by UriHerrera** [comment]
> small, but mindblowing feature request: how about implementing "runit"... to supplement portability and crossplatformity in 30 sec. timeframe ?

You're welcome to make a PR to test. I have no experience with runit.

**Comment by UriHerrera** [comment]
### Using OpenRC (update)
I have created another build based on the development branch; this build utilizes OpenRC as ***init*** whereas previously, OpenRC was the service manager, and SysV was the init.

Things that work:

- [x] Boots (No Plymouth though. The Plymouth version in use can work but not newer versions as they depend thoroughly on SystemD).
- [x] Persistence.
- [x] X11.
- [x] Network.
- [x] Bluetooth.
- [x] WiFi (At least with the chips that I have).
- [x] VFIO enablement.

Things that don't work:

- [ ] NX Firewall KCM (The UI is displayed, and UFW _does work_, but there's an error in KF5 auth, probably a sign that the code is getting old or that a service is not starting).

### Screenshots

![VirtualBox_Nitrux_23_04_2020_04_07_53](https://user-images.githubusercontent.com/3053525/80261219-66980a80-864f-11ea-9acb-b5173584f3a7.png)
> Test build using OpenRC is running on VirtualBox.

### What's next
OpenRC as *init* is working now. There are still some issues for it to be considered _stable_ such as:

* No, bootsplash. With SysV older Plymouth versions do work, so I _think_ that it should be possible to make it work with OpenRC although I haven't seen a distribution using (modern) Plymouth mostly because of its dependency for SystemD.

* Plasma _does work_ as the screenshot shows, however, it does present a problem of working "randomly." Sometimes it starts, sometimes it doesn't. We'd need to investigate why that is the case, but as far as whether it works or not, it does.

**Comment by UriHerrera** [comment]
I'm closing this as there's a working image with SysVinit, which will replace the current image files; meanwhile, OpenRC integration is polished to replace SysVinit eventually.
